[package]
name = "currentsong"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
ctrlc = { version = "3.0", features = ["termination"] }
dirs = "4.0"
open = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.23"
winapi = "0.3"

[profile.release]
opt-level = 's'
codegen-units = 1
lto = true
panic = "abort"
